/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-07 00:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/jspWorkspace/mNote/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/est_education/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/jspWorkspace/mNote/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/est_education/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/comn/component/include-body.jspf", Long.valueOf(1641455719672L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1641457850988L));
    _jspx_dependants.put("jar:file:/C:/jspWorkspace/mNote/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/est_education/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/comn/component/include-header.jspf", Long.valueOf(1641455719672L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n<meta charset=\"utf-8\">\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\" />\r\n<meta name=\"Generator\" content=\"\">\r\n<meta name=\"Author\" content=\"\">\r\n<meta name=\"Keywords\" content=\"\">\r\n<meta name=\"Description\" content=\"\">\r\n\r\n\r\n  \r\n\r\n\r\n<!-- css -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/>\r\n\r\n	<!-- favicon --> \r\n	<link rel=\"shortcut icon\" href=\"/dist/img/favicon.ico\" type=\"image/x-icon\">\r\n	<!-- Ionicons -->\r\n	<link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n	<!-- Font Awesome -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/fontawesome-free/css/all.min.css\">\r\n	<!-- Tempusdominus Bbootstrap 4 -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n	<!-- iCheck -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n	<!-- JQVMap -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/jqvmap/jqvmap.min.css\">\r\n	<!-- Theme style -->\r\n	<link rel=\"stylesheet\" href=\"/dist/css/adminlte.min.css\">\r\n	<!-- overlayScrollbars -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n	<!-- Daterange picker -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/daterangepicker/daterangepicker.css\">\r\n	<!-- summernote -->\r\n	<link rel=\"stylesheet\" href=\"/plugins/summernote/summernote-bs4.css\">\r\n");
      out.write("\r\n<!-- js.jquery(필요 시 수정) -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n	\r\n	<!-- jQuery -->\r\n	<script src=\"/plugins/jquery/jquery.min.js\"></script>\r\n	<!-- jQuery -->\r\n	<script src=\"/plugins/jquery/jquery.min.js\"></script>\r\n	<!-- jQuery UI 1.11.4 -->\r\n	<script src=\"/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n	<script>\r\n	  $.widget.bridge('uibutton', $.ui.button)\r\n	</script>\r\n	<!-- Bootstrap 4 -->\r\n	<script src=\"/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n	<!-- ChartJS -->\r\n	<script src=\"/plugins/chart.js/Chart.min.js\"></script>\r\n	<!-- Sparkline -->\r\n	<script src=\"/plugins/sparklines/sparkline.js\"></script>\r\n	<!-- JQVMap -->\r\n	<script src=\"/plugins/jqvmap/jquery.vmap.min.js\"></script>\r\n	<script src=\"/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\r\n	<!-- jQuery Knob Chart -->\r\n	<script src=\"/plugins/jquery-knob/jquery.knob.min.js\"></script>\r\n	<!-- daterangepicker -->\r\n	<script src=\"/plugins/moment/moment.min.js\"></script>\r\n	<script src=\"/plugins/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\r\n	<script src=\"/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n	<!-- Summernote -->\r\n	<script src=\"/plugins/summernote/summernote-bs4.min.js\"></script>\r\n	<!-- overlayScrollbars -->\r\n	<script src=\"/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\r\n	<!-- AdminLTE App -->\r\n	<script src=\"/dist/js/adminlte.js\"></script>\r\n	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n	<script src=\"/dist/js/pages/dashboard.js\"></script>\r\n	<!-- AdminLTE for demo purposes -->\r\n	<script src=\"/dist/js/demo.js\"></script>\r\n		\r\n	\r\n<!-- js.basic -->\r\n	<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" charset=\"utf-8\"></script>\r\n\r\n<!-- API -->\r\n	<!-- Google Font: Source Sans Pro -->\r\n	<link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n	<style>\r\n		 .sidebar {\r\n		   		width: 250px;\r\n		   	height: 140px;\r\n		   	overflow: auto;\r\n		 }\r\n		 .sidebar::-webkit-scrollbar {\r\n		   	width: 10px;\r\n		 }\r\n		 .sidebar::-webkit-scrollbar-thumb {\r\n		   	height: 17%;\r\n		   	background-color: rgba(255,255,255,1);\r\n		   /* 스크롤바 둥글게 설정    */\r\n		   	border-radius: 10px;;\r\n		 }\r\n		 .sidebar::-webkit-scrollbar-track {\r\n		   	background-color: rgba(0,0,0,0);\r\n		 }\r\n		 .AllScrollbar::-webkit-scrollbar {\r\n		  	width: 6px;\r\n		 }\r\n		 .AllScrollbar::-webkit-scrollbar-track {\r\n		  	background-color: transparent;\r\n		 }\r\n		 .AllScrollbar::-webkit-scrollbar-thumb {\r\n		  	border-radius: 3px;\r\n		  	background-color: gray;\r\n		 }\r\n		 .AllScrollbar::-webkit-scrollbar-button {\r\n		  	width: 0;\r\n		  	height: 0;\r\n		 }\r\n	</style>\r\n	\r\n	<script>\r\n	\r\n	\r\n		$(document).ready(function(){\r\n			\r\n			//사이드바 안에 소메뉴 숫자 카운트 및 표시\r\n");
      out.write("	        var beforeSystem      = $('#beforeSystem li').length;\r\n	        var beforeWork        = $('#beforeWork li').length;\r\n	        var beforeDevelopment = $('#beforeDevelopment li').length;\r\n	        var laterSystem       = $('#laterSystem li').length;\r\n	        var laterManagement   = $('#laterManagement li').length;\r\n	        var laterBusiness     = $('#laterBusiness li').length;\r\n	        var laterEducation    = $('#laterEducation li').length;\r\n	        var laterHrManagement = $('#laterHrManagement li').length;\r\n	        var laterSales        = $('#laterSales li').length;\r\n	        var laterDevelopment  = $('#laterDevelopment li').length;\r\n	        var laterStatistics   = $('#laterStatistics li').length;\r\n	        \r\n	        $(\"#beforeSystemCount\").html(beforeSystem);\r\n	        $(\"#beforeWorkCount\").html(beforeWork);\r\n	        $(\"#beforeDevelopmentCount\").html(beforeDevelopment);\r\n	        $(\"#laterSystemCount\").html(laterSystem);\r\n	        $(\"#laterManagementCount\").html(laterManagement);\r\n	        $(\"#laterBusinessCount\").html(laterBusiness);\r\n");
      out.write("	        $(\"#laterEducationCount\").html(laterEducation);\r\n	        $(\"#laterHrManagementCount\").html(laterHrManagement);\r\n	        $(\"#laterSalesCount\").html(laterSales);\r\n	        $(\"#laterDevelopmentCount\").html(laterDevelopment);\r\n	        $(\"#laterStatisticsCount\").html(laterStatistics);\r\n	        \r\n	    });\r\n	\r\n		//세션 체크 구 함수\r\n		var time = 1800;\r\n		var min = \"\";\r\n		var sec = \"\";\r\n		\r\n		var x = setInterval(function(){\r\n		 	min = parseInt(time/60);\r\n		 	sec = time % 60;\r\n		 	document.getElementById(\"sessionTime\").innerHTML = min + \"분\" + sec + \"초\";\r\n		 	time--;\r\n		 \r\n		 if(time < 0) {\r\n		  	clearInterval(x);\r\n		  	document.getElementById(\"sessionTime\").innerHTML = \"시간초과\";\r\n		  	alert(\"일정시간동안 동작이 없어 로그아웃되었습니다.\");\r\n		 }\r\n		}, 1000);\r\n\r\n	</script>\r\n	<title>(주)이에스티소프트 ERP</title>");
      out.write("\r\n\r\n<script>\r\n\r\n	$(document).ready(function(){\r\n		var comSubmit = new ComSubmit();\r\n		comSubmit.setUrl(\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\");\r\n		comSubmit.submit();\r\n	});\r\n	\r\n</script>\r\n</head>\r\n<body>\r\n	\r\n	");
      out.write("\r\n<form id=\"commonForm\" name=\"commonForm\"></form>");
      out.write("\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/comn/component/include-header.jspf(17,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/comn/component/include-header.jspf(90,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/js/basic/common.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /index.jsp(13,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/erp/sample/openSamplePage.do");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
